
version: 2

models:
    - name: OPP_AND_ACC_STG
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: BOOKING_T
      description: "A starter dbt model"
      columns:
          - name: opp_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
