
version: 2

models:
    - name: OPPORTUNITY
      description: "build the Account Table for the POC Model"
      columns:
          - name: NETSUITE_CONN_NET_SUITE_SALES_ORDER_NUMBER_C
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
